// Copyright 2020 CleverGo. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found
// in the LICENSE file.

package captchas

import "html/template"

// Captcha is an interface that captchas that generated by driver should implements.
type Captcha interface {
	// ID returns captcha ID.
	ID() string

	// Answer returns captcha answer.
	Answer() string

	// EncodeToString returns encoded base64 string.
	EncodeToString() string

	// HTMLField returns a template.HTML that includes captcha ID hidden input field
	// and media field(audio/img).
	HTMLField() template.HTML
}
